### ISSUE TITLE
 Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by harideva16** [stwind/gradle-jni#2]
I am using windows os with java 14 and cmake version 3.20.2.

      commandLine 'cmd', '-c', 'mkdir -p build/natives && cd build/natives && cmake ../.. && make'

![Capture](https://user-images.githubusercontent.com/88296348/129468653-a653a2ee-85c1-4153-abab-a9cf04a47ce6.PNG)

**build.gradle**

    plugins {
      id 'java'
      id 'java-library'
    }

    dependencies {
      testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
      testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.6.0'
    }

    test {
      useJUnitPlatform()
    }

    sourceSets {
      main {
        resources {
          srcDirs "src/main/resources", "build/natives/lib"
        }
      }
    }

    compileJava {
      options.compilerArgs += ["-h", file("src/main/include")]
    }

    task compileJNI {
      dependsOn compileJava

      doLast {
        exec {
          commandLine 'cmd', '-c', 'mkdir -p build/natives && cd build/natives && cmake ../.. && make'
        }
      }
    }

    clean.doFirst {
      delete fileTree('src/main/include') {
        include 'jni_*.h'
      }
    }

    processResources {
      dependsOn compileJNI
    }

    tasks.withType(Test) {
      systemProperty "java.library.path", "build/natives/lib"
      testLogging.showStandardStreams = false
    }

**output**

    11:15:40: Executing task 'Runner.main()'...

    Starting Gradle Daemon...
    Gradle Daemon started in 5 s 835 ms
    > Task :jni-lib:compileJava

    > Task :jni-lib:compileJNI
    Microsoft Windows [Version 10.0.19042.1110]
    (c) Microsoft Corporation. All rights reserved.

    D:\gradle-jni-master\jni-lib>
    > Task :jni-lib:processResources NO-SOURCE
    > Task :jni-lib:classes
    > Task :jni-lib:jar
    > Task :jni-runner:compileJava
    > Task :jni-runner:processResources NO-SOURCE
    > Task :jni-runner:classes

    > Task :jni-runner:Runner.main()
    Exception in thread "main" java.lang.ExceptionInInitializerError
	at jni.Runner.main(Runner.java:5)
    Caused by: java.lang.NullPointerException
	at jni.LibraryLoader.load(LibraryLoader.java:26)
	at jni.Tools.<clinit>(Tools.java:5)
	... 1 more

    > Task :jni-runner:Runner.main() FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':jni-runner:Runner.main()'.
    > Process 'command 'C:/Program Files/Java/jdk-14.0.2/bin/java.exe'' finished with non-zero exit value 1

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 25s
    5 actionable tasks: 5 executed
    11:16:07: Task execution finished 'Runner.main()'.

How can I solve this error ?

**Comment by harideva16** [comment]
What I did wrong in this line ?

      commandLine 'cmd', '-c', 'mkdir build\natives && cd build\natives && cmake ../.. && cmake -G "Ninja"'

![ninja](https://user-images.githubusercontent.com/88296348/129473383-744d863c-d98f-4e44-99c9-b443ed44f12e.PNG)
